[General]
logLevel = 2 #0 trace; 1 debug; 2 info
avatarSet = 0 #0 orginal, 1 variant 
hideFaction = false #some information could be a spoiler

# ----------------
# |1            2|
# |              |
# |              |
# |4            3|
# ----------------
# values with a 10 px space to the side
# 1) x -745, y 320
# 2) x 405, y 320
# 3) x 405, y 1105
# 4) x -745, y 1105
[Window]
xPos = 405
yPos = 320

[Mods]
handToHand = false #Hand to Hand - An Adamant Addon, lockpicking -> Hand to Hand, pickpocket -> Security